### PR TITLE
#15 consolidate comments

### PR DESCRIPTION
**Pull request by MihaiTudorP**

### CODE REVIEW

**Comment by mihairinzis** [comment]
I suppose the WIP status is for the upcoming tests.. :p

**Comment by MihaiTudorP** [comment]
> 
> 
> I suppose the WIP status is for the upcoming tests.. :p
yes, that's what it's for

**Comment by RaduCStefanescu** [comment]
Hi @MihaiTudorP can you please resolve the conflicts of this PR?

**Comment by aniri** [comment]
@RaduCStefanescu I tried to fix the PR conflicts :smiley: 

Small question about the PR changes though: why was the response type of `CommentController` -> `create` changed from `CommentDto` to the entity type?

**Comment by georgebejan** [comment]
Based on the recent discussions regarding "consolidating" comments I think that the description from #15 is no longer valid because comments will not be automatically "reflected" in the document, but an admin will manually edit the contents of the document.

So I think that the changes from this PR are no longer necessary. @RaduCStefanescu what do you think?

**Comment by RaduCStefanescu** [comment]
I think this PR is handling the approve/reject status of a comment, which we are still needing. Can you comment on this one @aniri ?

**Comment by aniri** [comment]
Yep @RaduCStefanescu , this PR handles approve/reject status for comments. It's probably just a small part of the issue of consolidating comments. @georgebejan what are the latest requirements for this feature? Could we update #15 ?

But for some reason, this PR also changes the return type of the create comment method:
```
CommentDto create(UUID nodeId, CommentDto commentDto);
Comment create(UUID nodeId, CommentDto commentDto);
```
I don't get why this was done :/

**Comment by georgebejan** [comment]
> 
> 
> Yep @RaduCStefanescu , this PR handles approve/reject status for comments. It's probably just a small part of the issue of consolidating comments. @georgebejan what are the latest requirements for this feature? Could we update #15 ?
> 
> But for some reason, this PR also changes the return type of the create comment method:
> 
> ```
> CommentDto create(UUID nodeId, CommentDto commentDto);
> Comment create(UUID nodeId, CommentDto commentDto);
> ```
> 
> I don't get why this was done :/

I think the change in the return type is just an oversight. That should not be changed. 
This PR needs a rebase after #139 was merged.

**Comment by aniri** [comment]
I think it should be ok now :pray:

**Pull request merged**
